In [4]:
import requests
import pandas as pd

In [5]:
link_file = "https://esploradati.istat.it/SDMXWS/rest/data/41_983"
headers = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}
print("Downloading data...")

Downloading data...

In [6]:
r = requests.get(link_file, headers=headers)
print(r.status_code)

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [ ]:
with open("../data_raw/data.csv", "wb") as f:
    f.write(r.content)

print("Data downloaded and saved to ../data_raw/data.csv")

Data downloaded and saved to ../data_raw/data.csv

In [ ]:
df_istat = pd.read_csv("../data_raw/data.csv")
df_istat.head()

Empty DataFrame
Columns: [Error during writing responce]
Index: []

In [ ]:
df_istat.shape

(0, 1)

In [ ]:
df_istat.columns

Index(['Error during writing responce'], dtype='str')

In [ ]:
df_istat.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 1 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Error during writing responce  0 non-null      object
dtypes: object(1)
memory usage: 132.0+ bytes

In [ ]:
df_istat.describe()

       Error during writing responce
count                              0
unique                             0
top                              NaN
freq                             NaN

CONCLUSION

The data has been successfully fetched from the ISTAT API and saved to a CSV file. 
Further data cleaning and analysis will be performed in the next steps.