In [1]:
import pandas as pd

In [2]:
df_istat = pd.read_csv("../data_raw/data.csv")
df_istat.head()

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,IT1:41_983(1.0),A,1001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,1001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,1001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:41_983(1.0),A,1001,KILLINJ,F,2004,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:41_983(1.0),A,1001,KILLINJ,F,2005,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_istat.info()

<class 'pandas.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   DATAFLOW          573552 non-null  str
 1   FREQ              573552 non-null  str
 2   REF_AREA          573552 non-null  int64
 3   DATA_TYPE         573552 non-null  str
 4   RESULT            573552 non-null  str
 5   TIME_PERIOD       573552 non-null  int64
 6   OBS_VALUE         573552 non-null  int64
 7   OBS_STATUS        0 non-null       float64
 8   NOTE_DS           0 non-null       float64
 9   NOTE_REF_AREA     0 non-null       float64
 10  NOTE_DATA_TYPE    0 non-null       float64
 11  NOTE_RESULT       0 non-null       float64
 12  NOTE_TIME_PERIOD  0 non-null       float64
 13  BASE_PER          0 non-null       float64
 14  UNIT_MEAS         0 non-null       float64
 15  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(3), str(4)
memory usage: 70.0 MB

In [4]:
df_istat.isnull().sum()

DATAFLOW                 0
FREQ                     0
REF_AREA                 0
DATA_TYPE                0
RESULT                   0
TIME_PERIOD              0
OBS_VALUE                0
OBS_STATUS          573552
NOTE_DS             573552
NOTE_REF_AREA       573552
NOTE_DATA_TYPE      573552
NOTE_RESULT         573552
NOTE_TIME_PERIOD    573552
BASE_PER            573552
UNIT_MEAS           573552
UNIT_MULT           573552
dtype: int64

In [5]:
df_istat.duplicated().sum()

np.int64(0)

In [6]:
df_istat.dtypes

DATAFLOW                str
FREQ                    str
REF_AREA              int64
DATA_TYPE               str
RESULT                  str
TIME_PERIOD           int64
OBS_VALUE             int64
OBS_STATUS          float64
NOTE_DS             float64
NOTE_REF_AREA       float64
NOTE_DATA_TYPE      float64
NOTE_RESULT         float64
NOTE_TIME_PERIOD    float64
BASE_PER            float64
UNIT_MEAS           float64
UNIT_MULT           float64
dtype: object

In [7]:
df_istat.columns.tolist()

['DATAFLOW',
 'FREQ',
 'REF_AREA',
 'DATA_TYPE',
 'RESULT',
 'TIME_PERIOD',
 'OBS_VALUE',
 'OBS_STATUS',
 'NOTE_DS',
 'NOTE_REF_AREA',
 'NOTE_DATA_TYPE',
 'NOTE_RESULT',
 'NOTE_TIME_PERIOD',
 'BASE_PER',
 'UNIT_MEAS',
 'UNIT_MULT']

In [8]:
df_istat = df_istat.drop(
    columns=[
        "OBS_STATUS",
        "NOTE_DS",
        "NOTE_REF_AREA",
        "NOTE_DATA_TYPE",
        "NOTE_RESULT",
        "NOTE_TIME_PERIOD",
        "BASE_PER",
        "UNIT_MEAS",
        "UNIT_MULT"
    ]
)

In [9]:
df_istat.columns.to_list()

['DATAFLOW',
 'FREQ',
 'REF_AREA',
 'DATA_TYPE',
 'RESULT',
 'TIME_PERIOD',
 'OBS_VALUE']

In [10]:
df_istat['DATAFLOW'].value_counts()

DATAFLOW
IT1:41_983(1.0)    573552
Name: count, dtype: int64

In [11]:
df_istat['FREQ'].value_counts()

FREQ
A    573552
Name: count, dtype: int64

In [12]:
a = df_istat['REF_AREA'].value_counts()
print("value counts are: ", a)
b = df_istat['REF_AREA'].nunique()
print("the number of unique values in the REF_AREA column is: ", b)

value counts are:  REF_AREA
1001     72
1002     72
1003     72
1004     72
1006     72
         ..
12144     3
13256     3
24128     3
25075     3
28108     3
Name: count, Length: 8578, dtype: int64
the number of unique values in the REF_AREA column is:  8578

In [13]:
df_istat['DATA_TYPE'].value_counts()

DATA_TYPE
KILLINJ    382368
ROADACC    191184
Name: count, dtype: int64

In [14]:
df_istat['RESULT'].value_counts()

RESULT
F    191184
M    191184
9    191184
Name: count, dtype: int64

In [15]:
c = df_istat['TIME_PERIOD'].value_counts()
print("value counts are: ", c)
d = df_istat['TIME_PERIOD'].nunique()
print("the number of unique values in the TIME_PERIOD column is: ", d)

value counts are:  TIME_PERIOD
2002    24306
2003    24306
2001    24303
2005    24303
2006    24303
2007    24303
2008    24303
2004    24300
2009    24300
2010    24282
2011    24276
2012    24276
2013    24276
2014    24177
2015    24141
2016    24000
2017    23934
2018    23862
2019    23745
2020    23712
2021    23712
2022    23712
2023    23703
2024    19017
Name: count, dtype: int64
the number of unique values in the TIME_PERIOD column is:  24

In [16]:
df_istat['OBS_VALUE'].describe()

count    573552.000000
mean         20.207603
std         245.813966
min           0.000000
25%           0.000000
50%           1.000000
75%           8.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

In [17]:
df_istat = df_istat.drop(columns=['DATAFLOW', 'FREQ'])

In [18]:
df_istat.columns.tolist()

['REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE']

In [19]:
import pandas as pd

df_situas = pd.read_csv("../data_raw/territori_situas.csv", sep=";")
df_situas.head()

,Codice Ripartizione geografica,Codice Regione,Codice Provincia (Storico),Codice Provincia/Uts,Codice Comune (alfanumerico),Codice Comune (numerico),Comune,Comune (dizione straniera),Sigla automobilistica,Capoluogo di Provincia/Uts,Capoluogo di Regione,Popolazione legale,Anno Censimento,Superficie (Kmq),Anno (Superficie),Popolazione residente,Anno (Popolazione residente)
0,1,1,1,201,1001,1001,Agliè,NaN,TO,0,0,2644,2011,"13,1462",2020,2545,2020
1,1,1,1,201,1002,1002,Airasca,NaN,TO,0,0,3819,2011,"15,7393",2020,3633,2020
2,1,1,1,201,1003,1003,Ala di Stura,NaN,TO,0,0,462,2011,"46,3315",2020,459,2020
3,1,1,1,201,1004,1004,Albiano d'Ivrea,NaN,TO,0,0,1791,2011,"11,7314",2020,1638,2020
4,1,1,1,201,1006,1006,Almese,NaN,TO,0,0,6303,2011,"17,8756",2020,6355,2020

In [20]:
df_situas.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Codice Ripartizione geografica  7903 non-null   int64
 1   Codice Regione                  7903 non-null   int64
 2   Codice Provincia (Storico)      7903 non-null   int64
 3   Codice Provincia/Uts            7903 non-null   int64
 4   Codice Comune (alfanumerico)    7903 non-null   int64
 5   Codice Comune (numerico)        7903 non-null   int64
 6   Comune                          7902 non-null   str
 7   Comune (dizione straniera)      124 non-null    str
 8   Sigla automobilistica           7811 non-null   str
 9   Capoluogo di Provincia/Uts      7903 non-null   int64
 10  Capoluogo di Regione            7903 non-null   int64
 11  Popolazione legale              7903 non-null   int64
 12  Anno Censimento                 7903 non-null   int64
 13  Superficie (Kmq)                7903 non-null   str
 14  Anno (Superficie)               7903 non-null   int64
 15  Popolazione residente           7903 non-null   int64
 16  Anno (Popolazione residente)    7903 non-null   int64
dtypes: int64(13), str(4)
memory usage: 1.0 MB

In [21]:
df_situas['Codice Comune (numerico)'].head()

0    1001
1    1002
2    1003
3    1004
4    1006
Name: Codice Comune (numerico), dtype: int64

In [22]:
df_comuni = df_situas[['Codice Comune (numerico)', 'Comune']]

In [23]:
df_comuni.head()

   Codice Comune (numerico)           Comune
0                      1001            Agliè
1                      1002          Airasca
2                      1003     Ala di Stura
3                      1004  Albiano d'Ivrea
4                      1006           Almese

In [24]:
df_comuni.info()

<class 'pandas.DataFrame'>
RangeIndex: 7903 entries, 0 to 7902
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Codice Comune (numerico)  7903 non-null   int64
 1   Comune                    7902 non-null   str
dtypes: int64(1), str(1)
memory usage: 123.6 KB

In [25]:
df_final = pd.merge(df_istat, df_comuni, how='left', left_on='REF_AREA', right_on='Codice Comune (numerico)')

In [26]:
df_final.head()

,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,Codice Comune (numerico),Comune
0,1001,KILLINJ,F,2001,10,1001.0,Agliè
1,1001,KILLINJ,F,2002,10,1001.0,Agliè
2,1001,KILLINJ,F,2003,7,1001.0,Agliè
3,1001,KILLINJ,F,2004,13,1001.0,Agliè
4,1001,KILLINJ,F,2005,2,1001.0,Agliè

In [27]:
df_final['Comune'].isnull().sum()

np.int64(24939)

In [28]:
df_final[(df_final['Comune'].isnull())]['REF_AREA'].value_counts()

REF_AREA
1168     72
41032    60
6064     57
6089     57
22027    57
         ..
12144     3
13256     3
24128     3
25075     3
28108     3
Name: count, Length: 676, dtype: int64

In [29]:
df_final = df_final.dropna(subset=['Comune'])